# Generated by Django 4.1.2 on 2022-12-08 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0002_alter_gallery_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="gallery", name="image", field=models.ImageField(upload_to=""),
        ),
    ]
